---
- name: OpenStack Service Setup
  hosts: all
  become: yes
  vars_files:
    - group_vars/Neutron.yml
    - group_vars/Horizon.yml
    - group_vars/Cinder.yml

  tasks:
    - name: Configure and Install Neutron
      include_role:
        name: Neutron

    - name: Configure and Install Horizon
      include_role:
        name: Horizon

    - name: Configure and Install Cinder
      include_role:
        name: Cinder
